export type Event = {
  id: number;
  title: string;
  description: string;
  event_type: "tournament" | "open_gym";
  gender: "mens" | "womens" | "coed";
  surface: "indoor" | "grass" | "beach";
  team_size: "6v6" | "4v4" | "3v3" | "2v2";
  skill_levels: string[] | null;
  event_date: string;
  start_time: string;
  end_time: string | null;
  address: string | null;
  cost: number;
  cost_type: "team" | "individual";
  capacity: number | null;
  registration_link: string | null;
  image_url: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  created_by: string;
};
